import type { Metadata } from "next";
import "@/styles/globals.css";
import { headers } from 'next/headers' // added
import ContextProvider from '@/context'
import MaxWrapper from "@/components/shared/MaxWrapper";
import NavBar from "@/components/shared/NavBar";
import { Toaster } from "sonner";
import ScrollToTopBtn from "@/components/shared/ScrollToTopBtn";
import BubbleCursor from "@/components/shared/BubbleCursor";

export const metadata: Metadata = {
  title: "PoolPlay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const headersObj = headers();
  const cookies = headersObj.get('cookie')

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="w-full min-h-screen antialiased bg-black"
      >
        <ContextProvider cookies={cookies}>
          <MaxWrapper>
            <NavBar />
            <main className="w-full">
              {children}
            </main>
            <ScrollToTopBtn />
            <Toaster richColors position="top-right" />
            {/* <Footer /> */}
          </MaxWrapper>
        </ContextProvider>
        <BubbleCursor />
      </body>
    </html>
  );
}
